# Generated by Django 6.0 on 2025-12-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecaPuntoSaber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='autor',
            field=models.CharField(default='Autor desconocido', max_length=200),
        ),
        migrations.AddField(
            model_name='archivo',
            name='categoria',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
