# Generated by Django 6.0 on 2025-12-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecaPuntoSaber', '0002_archivo_autor_archivo_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('eliminado_docente', 'Eliminado por docente'), ('eliminado_admin', 'Eliminado por administrador')], default='activo', max_length=30),
        ),
    ]
